all:
	g++ A_solver.cpp -O2 -Wno-unused-result -o A_solver
ans:
	./A_solver < ../datasets/A_Row/row01.in > row01.ans
	./A_solver < ../datasets/A_Row/row02.in > row02.ans
	./A_solver < ../datasets/A_Row/row03.in > row03.ans
	./A_solver < ../datasets/A_Row/row04.in > row04.ans
	./A_solver < ../datasets/A_Row/row05.in > row05.ans
	./A_solver < ../datasets/A_Row/row06.in > row06.ans
	./A_solver < ../datasets/A_Row/row07.in > row07.ans
	./A_solver < ../datasets/A_Row/row08.in > row08.ans
	./A_solver < ../datasets/A_Row/row09.in > row09.ans
	./A_solver < ../datasets/A_Row/row10.in > row10.ans
