all:
	g++ A_solver.cpp -O2 -Wno-unused-result -o A_solver
	g++ B_solver.cpp -O2 -Wno-unused-result -o B_solver
ans:
	./A_solver < ../datasets/A_Row/row01.in > row01.ans
	./A_solver < ../datasets/A_Row/row02.in > row02.ans
	./A_solver < ../datasets/A_Row/row03.in > row03.ans
	./A_solver < ../datasets/A_Row/row04.in > row04.ans
	./A_solver < ../datasets/A_Row/row05.in > row05.ans
	./A_solver < ../datasets/A_Row/row06.in > row06.ans
	./A_solver < ../datasets/A_Row/row07.in > row07.ans
	./A_solver < ../datasets/A_Row/row08.in > row08.ans
	./A_solver < ../datasets/A_Row/row09.in > row09.ans
	./A_solver < ../datasets/A_Row/row10.in > row10.ans
	./B_solver < ../datasets/B_Election/election01.in > election01.ans
	./B_solver < ../datasets/B_Election/election02.in > election02.ans
	./B_solver < ../datasets/B_Election/election03.in > election03.ans
	./B_solver < ../datasets/B_Election/election04.in > election04.ans
	./B_solver < ../datasets/B_Election/election05.in > election05.ans
	./B_solver < ../datasets/B_Election/election06.in > election06.ans
	./B_solver < ../datasets/B_Election/election07.in > election07.ans
	./B_solver < ../datasets/B_Election/election08.in > election08.ans
	./B_solver < ../datasets/B_Election/election09.in > election09.ans
	./B_solver < ../datasets/B_Election/election10.in > election10.ans

